apiVersion: v2
name: cyclops
description: Cyclops Helm chart
type: application
version: "0.14.1"
appVersion: "v0.15.4"
home: https://cyclops-ui.com/
keywords:
  - Devops
  - Kubernetes operator
icon: https://cyclops-ui.com/img/logo.png
