apiVersion: v2
name: cyclops-chart
description: Cyclops Helm chart
type: application
version: "0.10.0"
appVersion: "v0.15.2"
home: https://cyclops-ui.com/
keywords:
  - Devops
  - Kubernetes operator
