apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops-ctrl
  namespace: {{ include "cyclops.namespace" . | quote }}
  labels:
    app: cyclops-ctrl
spec:
  replicas: {{ ((.Values.ctrl).replicas) | default 1 }}
  selector:
    matchLabels:
      app: cyclops-ctrl
  template:
    metadata:
      labels:
        app: cyclops-ctrl
    spec:
      serviceAccountName: cyclops-ctrl
      containers:
        - name: cyclops-ctrl
          image: cyclopsui/cyclops-ctrl:v0.15.4
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            {{- if ((.Values.global).disableTelemetry) }}
            - name: DISABLE_TELEMETRY
              value: {{ ((.Values.global).disableTelemetry) | quote }}
            {{- end }}
            {{- include "cyclops-ctrl.watchNamespace" . | nindent 12 }}
            {{- include "cyclops-ctrl.moduleTargetNamespace" . | nindent 12 }}
            {{- include "cyclops-ctrl.watchNamespaceHelm" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
