{{- if eq ((.Values.global).singleNamespaceScope).enabled true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: ctrl
    app.kubernetes.io/name: cyclops-ctrl
    app.kubernetes.io/part-of: cyclops
  name: cyclops-ctrl
  namespace: {{ include "cyclops.namespace" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cyclops-ctrl
subjects:
  - kind: ServiceAccount
    name: cyclops-ctrl
    namespace: {{ include "cyclops.namespace" . | quote }}
{{- end }}
