apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ctrl
    app.kubernetes.io/name: cyclops-ctrl
    app.kubernetes.io/part-of: cyclops
  name: cyclops-ctrl
  namespace: cyclops